name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ "main" ] # This runs every time you push to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # These permissions are needed for the deploy action
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_FORMSPREE_ENDPOINT: ${{ secrets.VITE_FORMSPREE_ENDPOINT }}
          VITE_RESUME_URL: ${{ secrets.VITE_RESUME_URL }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist' # Tells GitHub where your built site is

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2